package sample.jsonrpc;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Sun Dec 09 16:55:08 EST 2012
 */

public interface Calculator {

    public Double add(Double a, Double b) throws com.bitmechanic.barrister.RpcException;
    public Double subtract(Double a, Double b) throws com.bitmechanic.barrister.RpcException;

}

