package sample.jsonrpc;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Sun Dec 09 16:55:08 EST 2012
 */
public class BarristerMeta {

    public static final Long DATE_GENERATED = 1355088599337L;
    public static final String CHECKSUM = "51a911b5eb0b61fbb9300221d8c37134";
    public static final String BARRISTER_VERSION = "0.1.4";

}

