package sample.jsonrpc;

import com.bitmechanic.barrister.HttpTransport;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Sun Dec 09 16:55:08 EST 2012
 */
public class CalculatorClient implements Calculator {

    private com.bitmechanic.barrister.Transport _trans;

    public CalculatorClient(com.bitmechanic.barrister.Transport trans) {
        trans.getContract().setPackage("jsonrpc");
        this._trans = trans;
    }

    public Double add(Double a, Double b) throws com.bitmechanic.barrister.RpcException {
        Object _params = new Object[] { a, b };
        com.bitmechanic.barrister.RpcRequest _req = new com.bitmechanic.barrister.RpcRequest(java.util.UUID.randomUUID().toString(), "Calculator.add", _params);
        com.bitmechanic.barrister.RpcResponse _resp = this._trans.request(_req);
        if (_resp == null) {
            return null;
        }
        else if (_resp.getError() == null) {
            return (Double)_resp.getResult();
        }
        else {
            throw _resp.getError();
        }
    }

    public Double subtract(Double a, Double b) throws com.bitmechanic.barrister.RpcException {
        Object _params = new Object[] { a, b };
        com.bitmechanic.barrister.RpcRequest _req = new com.bitmechanic.barrister.RpcRequest(java.util.UUID.randomUUID().toString(), "Calculator.subtract", _params);
        com.bitmechanic.barrister.RpcResponse _resp = this._trans.request(_req);
        if (_resp == null) {
            return null;
        }
        else if (_resp.getError() == null) {
            return (Double)_resp.getResult();
        }
        else {
            throw _resp.getError();
        }
    }

    public static void main(String argv[]) throws Exception {
        HttpTransport trans = new HttpTransport("http://127.0.0.1:8080/calc");
        CalculatorClient calc = new CalculatorClient(trans);

        System.out.println(String.format("1+5.1=%.1f", calc.add(1.0, 5.1)));
        System.out.println(String.format("8-1.1=%.1f", calc.subtract(8.0, 1.1)));

        System.out.println("\nIDL metadata:");

        // BarristerMeta is a Idl2Java generated class in the same package
        // as the other generated files for this IDL
        System.out.println("barrister_version=" + BarristerMeta.BARRISTER_VERSION);
        System.out.println("checksum=" + BarristerMeta.CHECKSUM);
    }

}

